<a href="https://colab.research.google.com/github/proditor002/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Structure (โครงสร้างข้อมูล)

การเก็บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นระเบียบ

### ```list()```

*   เก็บอะไรก็ได้
*   ลำดับในการเก็บ มีความสำคัญ



In [2]:
list_a = [1,2,3,4,5,6]  ##[ ] square brackets

In [3]:
list_a

[1, 2, 3, 4, 5, 6]

In [4]:
list_b = ['ab',2,3.14,list_a]

In [5]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### Indexing การชี้สมาชิกใน list ด้วยเลขลำดับของ list

In [6]:
list_a[3]   # ดึงข้อมูลตัวที่ 3 ของ list_a (เริ่มนับจาก 0,1,2,...,)

4

In [7]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [8]:
list_b[3][4]

5

In [9]:
list_a[-1]  ## index -1 คือตัวสุดท้ายของ list

6

In [10]:
list_a[-4]

3

## การสร้าง ```list()```

In [11]:
list_x1 = []  ## แบบที่ 1
list_x2 = list()  ## แบบที่ 2

In [12]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย ```append()```

In [44]:
list_x1.append(2)   # เพิ่ม 2 เข้าไปใน list_x1

In [45]:
list_x1

[2, 4, 2]

In [46]:
list_x1.append(4)       # เพิ่ม 4 เข้าไปใน list_x1
print(list_x1)          # run กี่รอบก็จะเพิ่มเข้าไปเท่านั้น

[2, 4, 2, 4]


In [47]:
list_x1[0]

2

In [48]:
list_x1[-1]

4

In [49]:
list_x2

['ha']

In [50]:
list_x2.append('ha')

In [51]:
list_x2   # run -> list_x2.append('ha') สองรอบ จะได้ ['ha', 'ha']

['ha', 'ha']

### ลบสมาชิกจาก list

In [52]:
list_x1.append('ha')

In [53]:
list_x1

[2, 4, 2, 4, 'ha']

In [54]:
list_x1.pop()        # ดึงตัวหลังสุดออกมา 

'ha'

In [55]:
list_x1

[2, 4, 2, 4]

### `len()` ตรวจสอบสมาชิกของ list

In [56]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [57]:
len(list_a)     # len จะนับจำนวนที่แท้จริง (เริ่มจาก 1 ไม่ใช่ 0)

6

### String is list of characters

In [58]:
st_stat = 'Department of Statistics, Faculty of Science'

In [59]:
st_stat[10]

' '

In [60]:
len(st_stat)

44

### List Slicing `:`
`list[จุดเริ่มต้น:จุดสุดท้าย)`

`list[จุดเริ่มต้น:จุดสุดท้าย:step)`

** step คือ กระโดดกี่ตัว

In [61]:
list_a

[1, 2, 3, 4, 5, 6]

In [62]:
list_a[2]       # ทำแบบนี้จะดึงมาได้แค่ตัวเดียว

3

#### `:` colon

In [63]:
list_a[-3:]     # ตัดมาแค่ 3 ตัวสุดท้าย

[4, 5, 6]

In [64]:
list_a[1:4]     # ตัด 2,3,4 มา   # เริ่มนับจาก 0,1,2,...

[2, 3, 4]

In [65]:
list_a[:]       # เอาทุกตัว

[1, 2, 3, 4, 5, 6]

#### step

In [66]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [67]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [68]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [69]:
list_c[::-1]        # ดึงจากท้ายมาหน้า (สลับ)

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### `range()`

In [70]:
range(21)       # range ความยาว 21 ตัว ค่า 0-20

range(0, 21)

In [71]:
a = list(range(21))

In [72]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [73]:
list(range(1,21))       # input 2 ตัว

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

## HW2 คำนวนเวลาเป็นวินาทีขอเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)
- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [75]:
#Ex 01:02:03

Ex = (1*60*60) + (2*60) + 3
print(f'01:02:03 แปลงเป็นวินาที ได้ {Ex00} วินาที')

NameError: ignored

In [76]:
#1 12:30:15

T1 = '12:30:15'
T1_sp = T1.split(':')
T1_sp = int(T1_sp[0])*60*60 + int(T1_sp[1])*60 + int(T1_sp[2])
print(f'{T1} แปลงเป็นวินาที ได้ {T1_sp} วินาที')

12:30:15 แปลงเป็นวินาที ได้ 45015 วินาที


In [77]:
#2 13:41:07

T2 = '13:41:07'
T2_sp = T2.split(':')
T2_sp = int(T2_sp[0])*60*60 + int(T2_sp[1])*60 + int(T2_sp[2])
print(f'{T2} แปลงเป็นวินาที ได้ {T2_sp} วินาที')

13:41:07 แปลงเป็นวินาที ได้ 49267 วินาที


In [78]:
#T3 09:11:50

T3 = '09:11:50'
T3_sp = T3.split(':')
T3_sp = int(T3_sp[0])*60*60 + int(T3_sp[1])*60 + int(T3_sp[2])
print(f'{T3} แปลงเป็นวินาที ได้ {T3_sp} วินาที')

09:11:50 แปลงเป็นวินาที ได้ 33110 วินาที


In [79]:
#T4 21:30:15

T4 = '21:30:15'
T4_sp = T4.split(':')
T4_sp = int(T4_sp[0])*60*60 + int(T4_sp[1])*60 + int(T4_sp[2])
print(f'{T4} แปลงเป็นวินาที ได้ {T4_sp} วินาที')

21:30:15 แปลงเป็นวินาที ได้ 77415 วินาที


In [80]:
#T5 03:10:15

T5 = '03:10:15'
T5_sp = T5.split(':')
T5_sp = int(T5_sp[0])*60*60 + int(T5_sp[1])*60 + int(T5_sp[2])
print(f'{T5} แปลงเป็นวินาที ได้ {T5_sp} วินาที')

03:10:15 แปลงเป็นวินาที ได้ 11415 วินาที


# Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่มีความสำคัญ

### สร้าง Dictionary

In [82]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # {} curly brackets

### การชี้สมาชิกใน Dictionary

In [85]:
dict_a[1] # Dict จะยืดยุ่นกว่า list เพราะสามารถกำหนด index อะไรก็ได้ และ index เรียกว่า key

'Happy'

In [84]:
dict_a['N']

'New'

In [86]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [87]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [89]:
dict_a[7] = 3.14 # dict a ที่มีสมาชิกเป็น 7 จะเพิ่ม 3.14

In [90]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [93]:
dict_a['N'] = 'NNNNEEEEWWWW'

In [94]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

## Numpy Array

- เก็บได้แค่ตัวเลข
- อ้างอิงโดยใช้พิกัด


In [95]:
import numpy

### 1D array

In [97]:
arr_a = numpy.array([1,2,3,4,5])

In [98]:
arr_a

array([1, 2, 3, 4, 5])

In [99]:
arr_a[0]

1

In [103]:
list_A = [1,2,3,4,5]

In [104]:
list_A

[1, 2, 3, 4, 5]

In [105]:
arr_a[0]

1

In [106]:
list_A[0]

1

In [107]:
5* arr_a # Matrix (scarlar multiplication)

array([ 5, 10, 15, 20, 25])

In [108]:
arr_b = numpy.array([10,20,30,40,50])

In [109]:
print(arr_a)

[1 2 3 4 5]


In [110]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

In [118]:
arr_a.shape # 1มิติ 5สมาชิก

(5,)

### 2D array

In [112]:
import numpy as np # อิมพอทแล้วเปลี่ยนชื่อให้มันเป็น Np

In [114]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [115]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
arr2_z.shape # 2แถว 3 หลัก

(2, 3)

`np.zeros()`

In [123]:
arr2_3_5_0 = np.zeros((3,5)) # array 3*5

In [122]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [128]:
arr2_3_5_0[1,2] = 9 # ใส่ค่าใน array

In [127]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [130]:
arr2_3_5_0[1,2] # การดึงค่าใน array

9.0

In [131]:
print(list_A) # เปลี่ยนค่าใน list()
list_A[-1] = 'Chrismas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Chrismas']


### `np.ones()`

In [133]:
arr2_4_5_1 = np.ones((4,5))

In [134]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [135]:
arr2_4_5_200 = 200*np.ones((4,5))

In [136]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix operation

#### การบวก ลบ  matrix $M \pm N$ บวกลบตัวที่อยู่ตำแหน่งเดียวกัน

In [140]:
arr2_4_5_200 +  arr2_3_5_0 # ตัวอย่าง error ถ้าบวก ลบแล้ว  shape ไม่เท่ากัน

ValueError: ignored

In [141]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

#### การคูณ Matrix 
- $aM$ scalar คูณ Matrix (scalarคูณกระจายเข้าไปทุกตัวของ Matrix)
- $M\times N$ Matrix คูณ Matrix (แถวคูณหลัก)

In [142]:
5 * arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

$M\times N$ (dot product)
- (m x n) $\times$ (n,o) = (m,o) (shape)

In [145]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [146]:
mat_a 

array([[2, 3, 5],
       [4, 6, 7]])

In [147]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [148]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

a x c , b x c  

In [149]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [150]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

cxa, cxb

In [151]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [152]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [153]:
mat_a * mat_b # คูณตัวตำแหน่งเดียวกัน

array([[  2,   6,  25],
       [  8,  24, -49]])

### Matrix Slicing

In [154]:
mat_X[:2,:2]

NameError: ignored

###HW 3 

1. สร้าง array ที่มีรูปต้นคริสมาสต์
2. slice เลข 1 ออกมาจาก array HW3

In [159]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [162]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0.]])